language: perl
matrix:
  include:
    - perl: "5.30"
      dist: xenial
    - perl: "5.22"
      dist: xenial
    - perl: "5.20"
      dist: trusty
    - perl: "5.18"
      dist: trusty
    - perl: "5.16"
      dist: trusty
    - perl: "5.14"
      dist: trusty
    - perl: "5.12"
      dist: trusty
    - perl: "5.10"
      dist: trusty
    - perl: "5.8"
      dist: trusty

env:
 - DISPLAY=:123
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq xvfb twm libx11-dev libfreetype6-dev libxft-dev
 - Xvfb :123 &
 - (sleep 10; env DISPLAY=:123 twm) &

branches:
 except:
  - /appveyor/
